# Generated by Django 5.1.7 on 2025-03-10 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoappGB', '0002_add_default_priorities'),
        ('todoappGB', '0002_alter_todoitem_useritem_alter_todoitem_description_and_more'),
    ]

    operations = [
    ]
